routes/web.php
<?php

use App\Models\Service;
use App\Models\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');


Route::group(['middleware' => ['auth']], function () {
    Route::name('user.')->group(function () {
        Route::get('/dashboard', function () {

            $user = User::all();
            $service = Service::all();

            // Count
            $countUser = $user->count();
            $countService = $service->count();

            return view('user.dashboard', [
                'user' => $user,
                'service' => $service,
            ]);
        })->name('dashboard');

        // Order
        Route::get('order', 'OrderController@index')->name('order.index');
        Route::get('order/create', 'OrderController@create')->name('order.create');
        Route::post('order/store', 'OrderController@store')->name('order.store');
        Route::get('order/{id}/edit', 'OrderController@edit')->name('order.edit');
        Route::put('order/{id}/update', 'OrderController@update')->name('order.update');
        Route::get('order/{id}/show', 'OrderController@show')->name('order.show');
        Route::delete('order/{id}/delete', 'OrderController@destroy')->name('order.destroy');
        Route::get('order/getService/{id}', 'OrderController@getService')->name('order.getService');
        Route::put('order/{id}/updateStatus', 'OrderController@updateStatus')->name('order.updateStatus');
        Route::put('order/{id}/uploadProof', 'OrderController@uploadProof')->name('order.uploadProof');


        // User Profile
        Route::get('profile', 'UserController@indexProfile')->name('user.profile');
        Route::put('profile', 'UserController@updateProfile')->name('user.profile.update');
    });
});

Route::group(['middleware' => ['auth', 'admin'], 'prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::name('admin.')->group(function () {
        Route::get('/dashboard', function () {

            $user = User::all();
            $service = Service::all();

            // Count
            $countUser = $user->count();
            $countService = $service->count();

            return view('dashboard', [
                'user' => $user,
                'service' => $service,
            ]);
        })->name('dashboard');

        // Service
        Route::get('service', 'ServiceController@index')->name('service.index');
        Route::get('service/create', 'ServiceController@create')->name('service.create');
        Route::post('service/store', 'ServiceController@store')->name('service.store');
        Route::get('service/{id}/edit', 'ServiceController@edit')->name('service.edit');
        Route::put('service/{id}/update', 'ServiceController@update')->name('service.update');
        Route::delete('service/{id}/delete', 'ServiceController@destroy')->name('service.destroy');

        // Order
        Route::get('order', 'OrderController@index')->name('order.index');
        Route::get('order/create', 'OrderController@create')->name('order.create');
        Route::post('order/store', 'OrderController@store')->name('order.store');
        Route::get('order/{id}/edit', 'OrderController@edit')->name('order.edit');
        Route::put('order/{id}/update', 'OrderController@update')->name('order.update');
        Route::get('order/{id}/show', 'OrderController@show')->name('order.show');
        Route::delete('order/{id}/delete', 'OrderController@destroy')->name('order.destroy');
        Route::get('order/getService/{id}', 'OrderController@getService')->name('order.getService');
        Route::put('order/{id}/updateStatus', 'OrderController@updateStatus')->name('order.updateStatus');

        // User
        Route::get('user', 'UserController@index')->name('user.index');
        Route::get('user/create', 'UserController@create')->name('user.create');
        Route::post('user/store', 'UserController@store')->name('user.store');
        Route::get('user/{id}/edit', 'UserController@edit')->name('user.edit');
        Route::put('user/{id}/update', 'UserController@update')->name('user.update');
        Route::delete('user/{id}/delete', 'UserController@destroy')->name('user.destroy');
    });
});

require __DIR__ . '/auth.php';

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use HasFactory;

    // fillable
    protected $fillable = [
        'user_id',
        'service_id',
        'status'
    ];

    // relation to user
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    // relation to service
    public function service()
    {
        return $this->belongsTo(Service::class);
    }

    // relation to order detail
    public function orderDetail()
    {
        return $this->hasOne(OrderDetail::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'phone',
        'address',
        'roles',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function admin()
    {
        return $this->roles === 'admin';
    }
}

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Order;
use App\Models\Service;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class OrderController extends Controller
{
    public function index()
    {
        $order = Order::all();

        return view('admin.order.index', [
            'orders' => $order
        ]);
    }

    public function create()
    {
        $service = Service::all();

        return view('admin.order.create', [
            'services' => $service
        ]);
    }

    public function store(Request $request)
    {
        $validate = $request->validate([
            'service_id' => 'required',
            'name' => 'required',
            'phone' => 'required',
            'email' => 'required',
            'address' => 'required',
            'area' => 'required',
            'schedule' => 'required',
        ]);

        $order = Order::create([
            'service_id' => $request->service_id,
            'user_id' => Auth::user()->id,
            'status' => 'pending',
        ]);

        if (!$order) {
            return redirect()->back()->with('error', 'Order gagal ditambahkan');
        }

        $order->orderDetail()->create([
            'name' => $request->name,
            'phone' => $request->phone,
            'email' => $request->email,
            'area' => $request->area,
            'address' => $request->address,
            'schedule' => $request->schedule,
            'message' => $request->message,
            'total' => $request->total,
        ]);

        return redirect()->route('admin.order.index')->with('success', 'Order ' . $order->id . ' berhasil ditambahkan');
    }

    public function edit($id)
    {
        $order = Order::find($id);

        if (!$order) {
            return redirect()->back()->with('error', 'Order tidak ditemukan');
        }

        $service = Service::all();

        return view('admin.order.edit', [
            'order' => $order,
            'services' => $service
        ]);
    }

    public function update(Request $request, $id)
    {
        $order = Order::findOrFail($id);

        if (!$order) {
            return redirect()->back()->with('error', 'Order tidak ditemukan');
        }

        $validate = $request->validate([
            'service_id' => 'required',
            'name' => 'required',
            'phone' => 'required',
            'email' => 'required',
            'address' => 'required',
            'area' => 'required',
            'schedule' => 'required',
            'message' => 'required',
            'total' => 'required',
            'status' => 'required',
            'proof_of_transfer' => 'nullable|image|mimes:jpg,png,jpeg|max:2048'
        ]);

        $order->update([
            'service_id' => $request->service_id,
            'status' => $request->status,
        ]);

        // Jika ada gambar yang diupload
        if ($request->hasFile('proof_of_transfer')) {
            // Hapus gambar lama
            if ($order->proof_of_transfer && file_exists(storage_path('app/public/' . $order->proof_of_transfer))) {
                Storage::delete('public/' . $order->proof_of_transfer);
            }

            // Upload gambar baru
            $file = $request->file('proof_of_transfer');
            $filename = time() . '.' . $file->getClientOriginalExtension();
            $file->storeAs('public/proof_of_transfer', $filename);

            $order->orderDetail()->update([
                'name' => $request->name,
                'phone' => $request->phone,
                'email' => $request->email,
                'area' => $request->area,
                'address' => $request->address,
                'schedule' => $request->schedule,
                'message' => $request->message,
                'total' => $request->total,
                'proof_of_transfer' => 'proof_of_transfer/' . $filename
            ]);
        }

        $order->orderDetail()->update([
            'name' => $request->name,
            'phone' => $request->phone,
            'email' => $request->email,
            'area' => $request->area,
            'address' => $request->address,
            'schedule' => $request->schedule,
            'message' => $request->message,
            'total' => $request->total,
        ]);


        return redirect()->route('admin.order.index')->with('success', 'Order ' . $order->id . ' berhasil diupdate');
    }


    public function show($id)
    {
        $order = Order::find($id);

        return view('admin.order.show', [
            'order' => $order
        ]);
    }

    public function destroy($id)
    {
        $order = Order::findOrFail($id);

        if (!$order) {
            return redirect()->back()->with('error', 'Order tidak ditemukan');
        }

        $order->delete();

        return redirect()->route('admin.order.index')->with('success', 'Order ' . $order->id . ' berhasil dihapus');
    }

    public function getService($id)
    {
        $service = Service::find($id);

        return response()->json($service);
    }

    public function updateStatus($id)
    {
        $order = Order::findOrFail($id);

        if (!$order) {
            return redirect()->back()->with('error', 'Order tidak ditemukan');
        }

        // Get button name
        $button = request()->input('button');

        if ($button == 'wait_payment') {
            $order->status = 'wait_payment';
        } else if ($button == 'canceled') {
            $order->status = 'canceled';
        }

        $order->update([
            'status' => $order->status
        ]);

        return redirect()->route('admin.order.index')->with('success', 'Order ' . $order->id . ' berhasil diupdate');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function index()
    {
        $user = User::all();

        return view('admin.user.index', [
            'user' => $user,
        ]);
    }

    public function create()
    {
        return view('admin.user.create');
    }

    public function store(Request $request)
    {
        // dd($request->all());
        $request->validate([
            'name' => 'required|min:3|max:255',
            'email' => 'required|email|unique:users,email',
            'password' => 'required|min:8|max:255',
            'role' => 'required|in:admin,user',
        ]);

        if ($request->password) {
            $password = bcrypt($request->password);

            User::create([
                'name' => $request->name,
                'email' => $request->email,
                'phone' => $request->phone ?? null,
                'address' => $request->address ?? null,
                'password' => $password,
                'role' => $request->role,
            ]);
        }

        return redirect()->route('admin.user.index')->with('success', 'User berhasil ditambahkan');
    }

    public function edit($id)
    {
        $user = User::findOrFail($id);

        return view('admin.user.edit', [
            'user' => $user,
        ]);
    }

    public function update(Request $request, $id)
    {
        // dd($request->all());
        $request->validate([
            'name' => 'required|min:3|max:255',
            'email' => 'required|email|unique:users,email,' . $id,
            'phone' => 'nullable|numeric',
            'address' => 'nullable|min:3|max:255',
            'password' => 'nullable|min:8|max:255',
            'role' => 'required|in:admin,user',
        ]);

        $name = $request->name;
        $email = $request->email;
        $phone = $request->phone;
        $address = $request->address;
        $role = $request->role;

        // If password is not empty, then update password
        if ($request->password) {
            $password = bcrypt($request->password);

            $user = User::findOrFail($id);
            $user->update([
                'name' => $name,
                'email' => $email,
                'phone' => $phone,
                'address' => $address,
                'password' => $password,
                'role' => $role,
            ]);
        } else {
            $user = User::findOrFail($id);
            $user->update([
                'name' => $name,
                'email' => $email,
                'phone' => $phone,
                'address' => $address,
                'role' => $role,
            ]);
        }

        return redirect()->route('admin.user.index')->with('success', 'User berhasil diupdate');
    }

    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();

        return redirect()->route('admin.user.index')->with('success', 'User berhasil dihapus');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    public function index()
    {
        return view('user.user.dashboard');
    }

    public function profile()
    {
        return view('user.user.profile');
    }

    // Index Profile
    public function indexProfile()
    {
        return view('user.user.profile');
    }

    public function updateProfile(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'email',
            'phone' => 'required|numeric',
            'address' => 'required|string|max:255',
        ]);

        $user = User::find(Auth::user()->id);
        $user->name = $request->name;
        $user->email = $request->email;
        $user->phone = $request->phone;
        $user->address = $request->address;

        $user->update([
            'name' => $request->name,
            'email' => $request->email,
            'phone' => $request->phone,
            'address' => $request->address
        ]);

        if ($user->save()) {
            return redirect()->back()->with('success', 'Profile berhasil diupdate');
        } else {


            return redirect()->back()->with('error', 'Profile gagal diupdate');
        }
    }
}

resources/views/user/order/index.blade.php
@extends('layouts.user')

@section('title', 'Pesanan')

@push('custom-css')
    {{-- Datatable --}}
    <link rel="stylesheet" href="{{ asset('core/node_modules/datatables.net-bs4/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('core/node_modules/datatables.net-select-bs4/css/select.bootstrap4.min.css') }}">
@endpush

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4>Data Layanan</h4>
                    {{-- Right button --}}
                    <div class="ml-auto">
                        {{-- Add Order Button --}}
                        <a href="{{ route('user.order.create') }}" class="btn btn-primary">
                            <i class="fas fa-plus"></i> Tambah Pesanan
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    @if (session('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <strong>Sukses!</strong> {{ session('success') }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                        </div>
                    @endif
                    {{-- Jika any error --}}
                    @if ($errors->any())
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <strong>Whoops!</strong> Terjadi kesalahan saat input data, yaitu:
                            <ul class="pl-4 my-2">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>

                            Mohon periksa kembali :)
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>

                        </div>
                    @endif
                    <div class="table-responsive">
                        <table class="table table-striped" id="table-1">
                            <thead>
                                <tr>
                                    <th class="text-center">
                                        #
                                    </th>
                                    <th>Nama</th>
                                    <th>Tipe Layanan</th>
                                    <th>Alamat</th>
                                    <th>Luas Area</th>
                                    <th>Harga (Per meter)</th>
                                    <th>Total</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {{-- Foreach --}}
                                @foreach ($orders as $item)
                                    <tr>
                                        <td>
                                            {{ $loop->iteration }}
                                        </td>
                                        <td>{{ $item->orderDetail->name }}</td>
                                        <td>{{ $item->service->name }}</td>
                                        <td>{{ $item->orderDetail->address }}</td>
                                        <td>{{ $item->orderDetail->area }}</td>
                                        <td>Rp. {{ number_format($item->service->price, 0, ',', '.') }}</td>
                                        <td>Rp. {{ number_format($item->orderDetail->total, 0, ',', '.') }}</td>
                                        <td>
                                            @if ($item->status == 'pending')
                                                <span class="badge badge-warning">Menunggu Konfirmasi</span>
                                            @elseif($item->status == 'wait_payment')
                                                <span class="badge badge-secondary">Menunggu Pembayaran</span>
                                            @elseif($item->status == 'waiting_confirmation')
                                                <span class="badge badge-info">Menunggu Konfirmasi</span>
                                            @elseif($item->status == 'confirmed')
                                                <span class="badge badge-info">Dikonfirmasi</span>
                                            @elseif($item->status == 'on_progress')
                                                <span class="badge badge-info">Diproses</span>
                                            @elseif($item->status == 'done')
                                                <span class="badge badge-success">Selesai</span>
                                            @elseif($item->status == 'canceled')
                                                <span class="badge badge-danger">Dibatalkan</span>
                                            @endif
                                        </td>
                                        <td>
                                            {{-- Show Button --}}
                                            <a href="{{ route('user.order.show', ['id' => $item->id]) }}"
                                                class="btn btn-success btn-sm">
                                                <i class="fas fa-eye"></i>
                                            </a>
                                            {{-- Edit --}}
                                            {{-- <a href="{{ route('user.order.edit', ['id' => $item->id]) }}"
                                                class="btn btn-primary btn-sm">
                                                <i class="fas fa-pencil-alt"></i>
                                            </a> --}}
                                            {{-- Form --}}
                                            {{-- <form action="{{ route('user.order.destroy', ['id' => $item->id]) }}"
                                                method="POST" class="d-inline">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger btn-sm"
                                                    onclick="return confirm('Apakah anda yakin ingin menghapus data ini?')">
                                                    <i class="fas fa-trash"></i>
                                                </button>
                                            </form> --}}
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('custom-modal')
    <div class="modal fade" tabindex="-1" role="dialog" id="addSparepartModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Tambah Data Layanan</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{{ route('admin.service.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf

                    <div class="modal-body">
                        <div class="form-group">
                            <label for="name">Nama</label>
                            <input type="text" class="form-control" id="name" name="name"
                                placeholder="Nama layanan" required>
                        </div>
                        <div class="form-group">
                            <label for="description">Deskripsi</label>
                            <textarea class="form-control" id="description" required name="description" placeholder="Deskripsi"></textarea>
                        </div>
                        <div class="form-group">
                            <label for="harga">Harga</label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <div class="input-group-text">
                                        Rp.
                                    </div>
                                </div>
                                <input required type="number" class="form-control" id="price" name="price"
                                    placeholder="Harga">
                                <div class="input-group-prepend">
                                    <div class="input-group-text">
                                        / Meter
                                    </div>
                                </div>
                                {{-- Input grup --}}
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer bg-whitesmoke br">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endpush

@push('custom-js')
    <script src="{{ asset('core/node_modules/datatables/media/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('core/node_modules/datatables.net-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('core/assets/js/page/modules-datatables.js') }}"></script>

    <script>
        function delete() {
            confirm("Apakah anda yakin ingin menghapus data ini?");
        }
    </script>
@endpush