routes/web.php
<?php

use App\Models\Service;
use App\Models\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');


Route::group(['middleware' => ['auth']], function () {
    Route::name('user.')->group(function () {
        Route::get('/dashboard', function () {

            $user = User::all();
            $service = Service::all();

            // Count
            $countUser = $user->count();
            $countService = $service->count();

            return view('user.dashboard', [
                'user' => $user,
                'service' => $service,
            ]);
        })->name('dashboard');

        // Order
        Route::get('order', 'OrderController@index')->name('order.index');
        Route::get('order/create', 'OrderController@create')->name('order.create');
        Route::post('order/store', 'OrderController@store')->name('order.store');
        Route::get('order/{id}/edit', 'OrderController@edit')->name('order.edit');
        Route::put('order/{id}/update', 'OrderController@update')->name('order.update');
        Route::get('order/{id}/show', 'OrderController@show')->name('order.show');
        Route::delete('order/{id}/delete', 'OrderController@destroy')->name('order.destroy');
        Route::get('order/getService/{id}', 'OrderController@getService')->name('order.getService');
        Route::put('order/{id}/updateStatus', 'OrderController@updateStatus')->name('order.updateStatus');
        Route::put('order/{id}/uploadProof', 'OrderController@uploadProof')->name('order.uploadProof');


        // User Profile
        Route::get('profile', 'UserController@indexProfile')->name('user.profile');
        Route::put('profile', 'UserController@updateProfile')->name('user.profile.update');
    });
});

Route::group(['middleware' => ['auth', 'admin'], 'prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::name('admin.')->group(function () {
        Route::get('/dashboard', function () {

            $user = User::all();
            $service = Service::all();

            // Count
            $countUser = $user->count();
            $countService = $service->count();

            return view('dashboard', [
                'user' => $user,
                'service' => $service,
            ]);
        })->name('dashboard');

        // Service
        Route::get('service', 'ServiceController@index')->name('service.index');
        Route::get('service/create', 'ServiceController@create')->name('service.create');
        Route::post('service/store', 'ServiceController@store')->name('service.store');
        Route::get('service/{id}/edit', 'ServiceController@edit')->name('service.edit');
        Route::put('service/{id}/update', 'ServiceController@update')->name('service.update');
        Route::delete('service/{id}/delete', 'ServiceController@destroy')->name('service.destroy');

        // Order
        Route::get('order', 'OrderController@index')->name('order.index');
        Route::get('order/create', 'OrderController@create')->name('order.create');
        Route::post('order/store', 'OrderController@store')->name('order.store');
        Route::get('order/{id}/edit', 'OrderController@edit')->name('order.edit');
        Route::put('order/{id}/update', 'OrderController@update')->name('order.update');
        Route::get('order/{id}/show', 'OrderController@show')->name('order.show');
        Route::delete('order/{id}/delete', 'OrderController@destroy')->name('order.destroy');
        Route::get('order/getService/{id}', 'OrderController@getService')->name('order.getService');
        Route::put('order/{id}/updateStatus', 'OrderController@updateStatus')->name('order.updateStatus');

        // User
        Route::get('user', 'UserController@index')->name('user.index');
        Route::get('user/create', 'UserController@create')->name('user.create');
        Route::post('user/store', 'UserController@store')->name('user.store');
        Route::get('user/{id}/edit', 'UserController@edit')->name('user.edit');
        Route::put('user/{id}/update', 'UserController@update')->name('user.update');
        Route::delete('user/{id}/delete', 'UserController@destroy')->name('user.destroy');
    });
});

require __DIR__ . '/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/admin/components/navbar.blade.php
<div class="navbar-bg"></div>
<nav class="navbar navbar-expand-lg main-navbar">
    <form class="form-inline mr-auto">
        <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
            <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i
                        class="fas fa-search"></i></a></li>
        </ul>
    </form>
    <ul class="navbar-nav navbar-right">
        <li class="dropdown"><a href="#" data-toggle="dropdown"
                class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                {{-- <img alt="image" src="../assets/img/avatar/avatar-1.png" class="rounded-circle mr-1"> --}}
                <div class="d-sm-none d-lg-inline-block">Hi, {{ Auth::user()->name }}</div>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                {{-- <a href="{{ route('user.profile') }}" class="dropdown-item has-icon">
                    <i class="far fa-user"></i> Profile
                </a> --}}

                <a href="{{ route('user.user.profile') }}" class="dropdown-item has-icon">
                    <i class="far fa-user"></i> Profile
                </a>
                <div class="dropdown-divider"></div>
                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    {{-- Logut --}}
                    <a class="dropdown-item has-icon text-danger" href="{{ route('login') }}"
                        onclick="event.preventDefault();
                    this.closest('form').submit();">
                        <i class="fas fa-sign-out-alt"></i> Logout
                    </a>

                </form>
            </div>
        </li>
    </ul>
</nav>

resources/views/admin/components/sidebar.blade.php
<div class="main-sidebar sidebar-style-2">
    <aside id="sidebar-wrapper">
        <div class="sidebar-brand">
            <a href="index.html">Waterproofing </a>
        </div>
        <div class="sidebar-brand sidebar-brand-sm">
            <a href="index.html">SM</a>
        </div>
        <ul class="sidebar-menu">
            <li class="menu-header">Dashboard</li>
            <li class="@if (Request::segment(2) == 'dashboard') active @endif"><a class="nav-link"
                    href="{{ route('admin.dashboard') }}"><i class="fas fa-home"></i>
                    <span>Dashboard</span></a>
            </li>
            <li class="menu-header">Master Data</li>
            <li class="@if (Request::segment(2) == 'service') active @endif"><a class="nav-link"
                    href="{{ route('admin.service.index') }}"><i class="fas fa-tools"></i>
                    <span>Layanan</span></a>
            </li>
            <li class="@if (Request::segment(2) == 'order') active @endif"><a class="nav-link"
                    href="{{ route('admin.order.index') }}"><i class="fas fa-shopping-cart"></i>
                    <span>Pesanan</span></a>
            </li>
            <li class="@if (Request::segment(2) == 'user') active @endif"><a class="nav-link"
                    href="{{ route('admin.user.index') }}"><i class="fas fa-users"></i>
                    <span>Pengguna</span></a>
            </li>
        </ul>
    </aside>
</div>